version: "3"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    container_name: clickhouse-server

  clickhouse-keeper:
    image: clickhouse/clickhouse-keeper
    container_name: clickhouse-keeper

  microservice:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./microservice/Dockerfile
    ports:
      - "8000:8000"